---
- hosts: all
  become: true

  tasks:

    - name: Add commands to .bashrc
      lineinfile:
        path: /home/vagrant/.bashrc
        line: '{{ item }}'
        create: yes
      with_items:
        - 'source /home/vagrant/vagrant_venv/bin/activate'
        - 'cd /vagrant'
