"""empty message

Revision ID: 36fefc317ad0
Revises: 002
Create Date: 2025-11-25 18:36:48.437814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36fefc317ad0'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.drop_constraint('ds_meta_data_ibfk_1', type_='foreignkey')
        batch_op.drop_column('ds_metrics_id')

    op.drop_table('ds_metrics')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.alter_column('logo_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csv_file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('row_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('column_names', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ds_metrics_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('ds_meta_data_ibfk_1'), 'ds_metrics', ['ds_metrics_id'], ['id'])

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('column_names')
        batch_op.drop_column('row_count')
        batch_op.drop_column('csv_file_path')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.alter_column('logo_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    op.create_table('ds_metrics',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('number_of_models', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('number_of_features', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
