"""Make logo_path NULL

Revision ID: e58be4261d2a
Revises: f1faa004868f
Create Date: 2025-11-11 16:34:29.909409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e58be4261d2a'
down_revision = 'f1faa004868f'
branch_labels = None
depends_on = None


def upgrade():
    # ### Comandos manuales para evitar Foreign Key Constraint Error (Error 1451) ###
    # Desactivamos temporalmente las comprobaciones de FK para permitir el DROP TABLE.
    op.execute('SET FOREIGN_KEY_CHECKS = 0;')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    
    # Volvemos a activar las comprobaciones de FK
    op.execute('SET FOREIGN_KEY_CHECKS = 1;')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.alter_column('logo_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.alter_column('logo_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    
    # ### end Alembic commands ###